#!/bin/sh

codesign() {

	local f="$1"

	if [ -n "${DO_SIGN}" ]; then
		echo "Signing '${f}'"
		"${OSSLSIGNCODE}" \
			-pkcs12 "${SIGN_PKCS12}" \
			-pass "${SIGN_PKCS12_PASS}" \
			-t "${SIGN_TIMESTAMP_URL}" \
			-in "${f}" \
			-out "${f}.tmp" \
			|| die "Cannot sign '${f}'"
			rm "${f}"
			mv "${f}.tmp" "${f}" || die "Cannot move into '${f}'"
	fi
}
